language: ruby
before_install: gem install bundler -v 1.10.5
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - jruby-19mode
  - rbx-2
env:
  - RSPEC_VERSION="<2.99"
  - RSPEC_VERSION="~>3.0
  - CODECLIMATE_REPO_TOKEN=561cc65a0f136c90b4661c76c96e4ca0717d49a1336cb08d7a617f2cb7d4f6c6
